# print('Olá mundo!')

#pais = ("Brasil", "Argentina", "Italia", "Equador", "Uruguai", "Espanha", "Nigeria")
#print(pais[1:5])
#print(pais[4])
#print(pais[4][2:5])

#carro = input("Usuario informe o nome do carro: ")
#print("O nome do carro é " + carro)
# carro = input("Por favor, insira o modelo do carro: ")
# moto = input("Por favor, insira o modelo da moto: ")
# print("O modelo do carro é " + carro + " e o modelo da moto é " + moto + ".")
# x = int(input("Quantas vezes você quer imprimir o modelo do carro?"))
# print(carro*x)
# print(input("Modelo do Carro: ") * int(input("Número de Vezes: ")))
# carro = input("Informe o modelo de um carro: ")
# print(carro + " " + str(len(carro)))
# carro1 = input("Informe o nome do carro A: ")
# carro2 = input("Informe o nome do carro B: ")
# separador = input("Escolha o separador de sua preferência (// ** $$ && \): ")
# print(f'{carro1}{separador}{carro2}')
# print(carro1, separador, carro2)
print("yes"*5)
